# Generated by Django 3.2.25 on 2025-10-26 15:03

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryClimber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token de Validação')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verificado')),
                ('email_verification_sent', models.DateTimeField(blank=True, null=True, verbose_name='Verificação Enviada')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('access_until', models.DateTimeField(default=core.models.get_default_access_until, verbose_name='Acesso até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_access', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('access_count', models.IntegerField(default=0, verbose_name='Número de Acessos')),
            ],
            options={
                'verbose_name': 'Escalador Temporário',
                'verbose_name_plural': 'Escaladores Temporários',
                'ordering': ['-created_at'],
            },
        ),
    ]
